# same as Ruby lib
repo_token: $COVERALLS_REPO_TOKEN # should be kept secret!
service_name: travis-ci # travis-ci or travis-pro

# for php-coveralls
coverage_clover: tests/_output/coverage.xml
json_path: tests/_output/coveralls-upload.json
