language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master
    - develop

cache:
  apt: true
  directories:
  - vendor
  - $HOME/.composer/cache

# Set the global environment variables
env:
  global:
    - WP_CORE_DIR: /tmp/wordpress
    - WP_VERSION: latest
    - COVERAGE: false

# Set the various variables for the environments to test
matrix:
  include:
#    - php: 5.5
#      env: WP_MULTISITE=0 PHP_UNIT_VERSION=4.8
#    - php: 5.6
#      env: WP_MULTISITE=0 PHP_UNIT_VERSION=4.8
#    - php: 7.0
#      env: WP_MULTISITE=0 PHP_UNIT_VERSION=5.7
    - php: 7.1
      env: WP_MULTISITE=0 PHP_UNIT_VERSION=6.3 COVERAGE=true APIGEN_DOCS=true LINT_SCHEMA=true
#    - php: 5.5
#      env: WP_MULTISITE=1 PHP_UNIT_VERSION=4.8
#    - php: 5.6
#      env: WP_MULTISITE=1 PHP_UNIT_VERSION=4.8
#    - php: 7.0
#      env: WP_MULTISITE=1 PHP_UNIT_VERSION=5.7
#    - php: 7.1
#      env: WP_MULTISITE=1 PHP_UNIT_VERSION=6.3
  fast_finish: true

install:
  - cd $TRAVIS_BUILD_DIR
  # Install composer packages, will also trigger dump-autoload
  - composer install
  # Install WP CLI
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp

before_script:
  # Install WordPress and the Test Suite
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  # Update composer
  - composer self-update
  # Install APIGen and PHPUnit, using the specified version for the PHP version we're running
  - composer require apigen/apigen:^4.1 phpunit/phpunit:$PHP_UNIT_VERSION
  - composer install --no-interaction
  # Make a directory for storing logs
  - mkdir -p build/logs
  - ls -al

script:
 # Execute unit tests with coverage if specified, otherwise without coverage
 - |
    if [ $COVERAGE == true ]; then
      vendor/bin/phpunit --group ajax
      vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    else
      vendor/bin/phpunit --group ajax --no-coverage
      vendor/bin/phpunit --no-coverage
    fi

after_success:
  # Install coveralls.phar
  # Upload coverage to coveralls
  - |
    if [ $COVERAGE == true ]; then
      wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      chmod +x coveralls.phar
      php coveralls.phar --version
      travis_retry php coveralls.phar -v
    fi
  # Install GraphQL Schema Linter
  # Move to the WordPress Install
  # Generate the Static Schema
  # Lint the Schema
  - |
    if [ $LINT_SCHEMA == true ]; then
      npm install -g graphql-schema-linter
      cd $WP_CORE_DIR
      wp graphql generate-static-schema
      graphql-schema-linter $TRAVIS_BUILD_DIR/wp-graphql/wp-graphql/schema.graphql
    fi
  # Generate the APIGen Docs
  - |
    if [ $APIGEN_DOCS == true ]; then
      cd $TRAVIS_BUILD_DIR
      vendor/bin/apigen generate --source="src" --destination $TRAVIS_BUILD_DIR/apigen --template-theme bootstrap
    fi

deploy:
  - provider: pages
    github_token: $APIGEN_GITHUB_TOKEN
    local_dir: $TRAVIS_BUILD_DIR/apigen
    repo: wp-graphql/wp-graphql-api-docs
    target_branch: master
    skip_cleanup: true
    on:
      all_branches: develop
