# This file is intended to be applied with 'docker-compose.local-app.yml'
version: "3.4"

services:
  wpgraphql.test:
    build:
      context: '.'
      args:
        DESIRED_WP_VERSION: "${WP_VERSION:-5.0.2}"
        DESIRED_PHP_VERSION: "${PHP_VERSION:-7.2}"
    image: "wordpress-wp-graphql"
    environment:
      # XDebug remote debugging: https://xdebug.org/docs/remote
      # Getting XDebug+Docker+PHPStorm working: https://serversforhackers.com/c/getting-xdebug-working
      XDEBUG_CONFIG: "remote_enable=1 remote_autostart=1 remote_connect_back=0 idekey=wpgraphql remote_host=${DOCKER_HOST_IP}"
      PHP_IDE_CONFIG: 'serverName=wpgraphql'
