version: "3"

services:
  wpgraphql.test:
    build:
      context: '../../.'
      args:
        BASE_DOCKER_IMAGE: "wordpress:${WP_VERSION}-php${PHP_VERSION}-apache"
    image: 'wpgraphql-cache'
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: 'mysql_test'
      WORDPRESS_DB_NAME: 'wpgraphql_test'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'testing'

  mysql_test:
    image: "${MYSQL_DOCKER_IMAGE}"
    environment:
      MYSQL_DATABASE: 'wpgraphql_test'
      MYSQL_ROOT_PASSWORD: 'testing'
