version: "3.4"

services:

  wpgraphql.test:
    build:
      context: '../'
      dockerfile: 'Dockerfile.sut-and-tester'
      target: 'wordpress-wp-graphql-sut'
      args:
        DESIRED_WP_VERSION: "${WP_VERSION:-5.0.2}"
        DESIRED_PHP_VERSION: "${PHP_VERSION:-7.2}"
    image: 'wordpress-wp-graphql-sut-cache'
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: 'mysql_test'
      WORDPRESS_DB_NAME: 'wpgraphql_test'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'testing'
    volumes:
      - '../:/var/www/html/wp-content/plugins/wp-graphql:ro'

  mysql_test:
    image: 'mariadb:10.2.20-bionic'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'wpgraphql_test'
      MYSQL_ROOT_PASSWORD: 'testing'
