# This file is intended to override "docker/docker-compose.tests.yml"
version: "3.4"

services:

  wpgraphql-tester:
    build:
      target: 'wordpress-wp-graphql-tester-shell'
    image: 'wordpress-wp-graphql-tester-shell-cache'
    container_name: 'wpgraphql-tester-shell'
    volumes:
      - '../bin:/tmp/wordpress/wp-content/plugins/wp-graphql/bin:rw'
      - '../cli:/tmp/wordpress/wp-content/plugins/wp-graphql/cli:rw'
      - '../src:/tmp/wordpress/wp-content/plugins/wp-graphql/src:rw'
      - '../tests:/tmp/wordpress/wp-content/plugins/wp-graphql/tests:rw'
      - '../phpcs.ruleset.xml:/tmp/wordpress/wp-content/plugins/wp-graphql/phpcs.ruleset.xml:rw'
      - '../phpunit.xml.dist:/tmp/wordpress/wp-content/plugins/wp-graphql/phpunit.xml.dist:rw'
      - '../schema.graphql:/tmp/wordpress/wp-content/plugins/wp-graphql/schema.graphql:rw'
      - '../wp-graphql.php:/tmp/wordpress/wp-content/plugins/wp-graphql/wp-graphql.php:rw'

  wpgraphql.test:
    volumes:
      - '../:/var/www/html/wp-content/plugins/wp-graphql:ro'
