# This file is intended to override "docker/docker-compose.tests.yml"
version: "3.4"

services:

  wpgraphql-tester:
    container_name: 'wpgraphql-tester-shell'
    volumes:
      - '../src:/tmp/wordpress/wp-content/plugins/wp-graphql/src:ro'
      - '../tests/acceptance:/tmp/wordpress/wp-content/plugins/wp-graphql/tests/acceptance:ro'
      - '../tests/functional:/tmp/wordpress/wp-content/plugins/wp-graphql/tests/functional:ro'
      - '../tests/wpunit:/tmp/wordpress/wp-content/plugins/wp-graphql/tests/wpunit:ro'
      - '../wp-graphql.php:/tmp/wordpress/wp-content/plugins/wp-graphql/wp-graphql.php:ro'
    entrypoint: [ "docker-entrypoint.tester-shell.sh" ]

  wpgraphql.test:
    volumes:
      - '../src:/var/www/html/wp-content/plugins/wp-graphql/src:ro'
      - '../wp-graphql.php:/var/www/html/wp-content/plugins/wp-graphql/wp-graphql.php:ro'
