version: "3.4"

services:
  wpgraphql.test:
    image: "wordpress:${WP_VERSION:-5.0.2}-php${PHP_VERSION:-7.2}-apache"
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: 'mysql_test'
      WORDPRESS_DB_NAME: 'wpgraphql_test'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'testing'
    volumes:
      - '../:/var/www/html/wp-content/plugins/wp-graphql:ro'
      - './uploads.txt:/usr/local/etc/php/conf.d/uploads.ini:ro'

  mysql_test:
    image: 'mariadb:10.2.21-bionic'
    environment:
      MYSQL_DATABASE: 'wpgraphql_test'
      MYSQL_ROOT_PASSWORD: 'testing'
