# This file is intended to be applied after 'docker-compose.yml'
version: "3.4"

services:
  wpgraphql.test:
    build:
      context: '../../../'
      target: 'wordpress-xdebug'
      args:
        DESIRED_WP_VERSION: "${WP_VERSION}"
        DESIRED_PHP_VERSION: "${PHP_VERSION}"
    environment:
      # XDebug remote debugging: https://xdebug.org/docs/remote
      # Getting XDebug+Docker+PHPStorm working: https://serversforhackers.com/c/getting-xdebug-working
      XDEBUG_CONFIG: "remote_enable=1 remote_connect_back=0 idekey=wpgraphql remote_host=${DOCKER_HOST_IP}"
      PHP_IDE_CONFIG: 'serverName=wpgraphql'
