# This workflow tracks changes to the "packages" and "build" directories
# and if changes are detected, we run npm scripts to re-build the GraphiQL app
# and commit the changes
name: build-graphiql

on:
  pull_request:
    paths:
      - "build/**"
      - "packages/**"
  push:
    paths:
      - "build/**"
      - "packages/**"
    branches:
      - develop
      - master

jobs:
  # Check to see if changes were made to the packages directory or the build directory in the PR
  check-for-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            packages:
              - 'packages/**'

      - name: Install Deps
        # Build GraphiQL only if changes were made to packages or build directory
        if: steps.filter.output.packages == 'true'
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            id: checkout
            with:
              ref: ${{ github.head_ref }}
              token: ${{ secrets.PAT }}

          # Install and build the GraphiQL App
          - name: Install NPM Dependencies and Build the GraphiQL App
            id: install-and-build
            run: |
              npm ci && npm run build

          # Commit the built assets for GraphiQL back to the repo
          - name: Commit built GraphiQL
            id: commit-changes
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
              commit_message: Apply GraphiQL build changes
              push_options: --force
