name: Deploy Docker Image

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  release:
    types: [published]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        env:
          PHP_VERSION: 7.4
          WP_VERSION: 5.6
        run: composer build-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: ghcr.io/markkelnar/wp-graphql:latest-wp5.6-php7.4
