name: Deploy Docker Image

# Note: testing image push process. On merge to develop branch, push the image.
# TODO: Add matrix for versions of WP and PHP.
# TODO: Deploy when release is tagged. Add release version to image name.
on:
  push:
    branches:
      - develop
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: ghcr.io/wp-graphql/wp-graphql:latest-wp5.6-php7.4
          file: docker/app.Dockerfile
          build-args: |
            PHP_VERSION=7.4
            WP_VERSION=5.6
