name: Schema Linter

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  run:
    runs-on: ubuntu-latest
    name: Lint WPGraphQL Schema
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP w/ Composer & WP-CLI
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mbstring, intl, bcmath, exif, gd, mysqli, opcache, zip, pdo_mysql
          coverage: none
          tools: composer, wp-cli

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Setup GraphQL Schema Linter
        run: npm install -g graphql-schema-linter

      - name: Setup MySQL
        run: |
            sudo systemctl start mysql.service
            echo 'CREATE DATABASE `wptests`;' | mysql -u root -p root

      - name: Setup WordPress
        run: |
          bin/install-test-env.sh wptests root root 127.0.0.1 latest true

      - name: Generate the Static Schema
        # 💡 Neutralize for now
        run: |
          cd /tmp/wordpress/
          # Output: /tmp/schema.graphql
          wp graphql generate-static-schema
          cd /tmp/wordpress/wp-content/plugins/wp-graphql/
          graphql-schema-linter /tmp/schema.graphql || true
