name: Schema Linter

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  run:
    runs-on: ubuntu-latest
    name: Lint WPGraphQL Schema
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: wptests
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Verify MySQL connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP w/ Composer & WP-CLI
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mbstring, intl, bcmath, exif, gd, mysqli, opcache, zip, pdo_mysql
          coverage: none
          tools: composer, wp-cli

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Setup GraphQL Schema Linter
        run: npm install -g graphql-schema-linter

      - name: Setup WordPress
        run: |
          composer run install-test-env

      - name: Generate the Static Schema
        # 💡 Neutralize for now
        run: |
          cd /tmp/wordpress/
          # Output: /tmp/schema.graphql
          wp graphql generate-static-schema
          cd /tmp/wordpress/wp-content/plugins/wp-graphql/
          graphql-schema-linter /tmp/schema.graphql || true
