name: Testing Integration

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
    paths:
      - '**.php'
      - '.github/workflows/*.yml'
      - '!docs/**'

jobs:
  continuous_integration:
    name: WordPress ${{ matrix.wordpress }} on PHP ${{ matrix.php }} ${{ matrix.multisite && 'Multisite' || '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '7.3' ]
        wordpress: [ '5.9', '5.8', '5.7.2', '5.6.2' ]
        include:
          - php: '8.1'
            wordpress: '6.0'
          - php: '8.0'
            wordpress: '6.0'
          - php: '7.4'
            wordpress: '6.0'
          - php: '8.0'
            wordpress: '5.9'
          - php: '8.0'
            wordpress: '5.9'
            multisite: 1
          - php: '8.0'
            wordpress: '5.8'
          - php: '7.4'
            wordpress: '5.8'
            coverage: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: json, mbstring
      
      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-dev"

      - name: Build "testing" Docker Image
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: composer build-test

      - name: Run Functional Tests w/ Docker.
        env:
          COVERAGE: ${{ matrix.coverage }}
          USING_XDEBUG: ${{ matrix.coverage }}
          DEBUG: ${{ matrix.debug }}
          SKIP_TESTS_CLEANUP: ${{ matrix.coverage }}
          SUITES: functional
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: composer run-test

      - name: Run WPUnit Tests w/ Docker.
        env:
          COVERAGE: ${{ matrix.coverage }}
          USING_XDEBUG: ${{ matrix.coverage }}
          DEBUG: ${{ matrix.debug }}
          SKIP_TESTS_CLEANUP: ${{ matrix.coverage }}
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
          MULTISITE: ${{ matrix.multisite }}
        run: composer run-test

      - name: Push Codecoverage to Coveralls.io
        if: ${{ matrix.coverage == 1 }}
        env:
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: vendor/bin/php-coveralls -v
